name: Build
concurrency:
  group: build-eden-${{ github.ref }}-${{ github.event.inputs.job_to_run || 'all' }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        type: choice
        description: 'Choose target build platform'
        options:
          - appimage
          - info
        default: 'appimage'

jobs:
  info:
    if: github.event.inputs.job_to_run == 'all' || github.event.inputs.job_to_run == 'info'
    runs-on: self-hosted
    name: "Get info"
    strategy:
      matrix:
        target: [Info]
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false

      - name: Get the latest release count
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          api_url="https://api.github.com/repos/${{ github.repository }}"
          latest_release_info=$(curl -H "Authorization: token $GH_TOKEN" "$api_url/releases/latest")
          last_release_tag=$(echo "$latest_release_info" | jq -r '.tag_name')
          echo "${last_release_tag}"
          old_count="${last_release_tag##*-}"
          echo "OLD_COUNT=$old_count" >> "$GITHUB_ENV"

      - name: Generate changelog
        run: |
          chmod +x ./changelog.sh
          ./changelog.sh

      - name: Upload tag file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: tag
          path: ~/tag

      - name: Upload count file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: count
          path: ~/count

      - name: Upload changelog file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: changelog
          path: ~/changelog

      - name: Upload source code
        uses: actions/upload-artifact@v4.6.2
        with:
          name: source
          path: artifacts

  appimage:
    if: github.event.inputs.job_to_run == 'all' || github.event.inputs.job_to_run == 'appimage'
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - target: common-pgo
            runs-on: self-hosted
            ccache: 'flase'
    container: ghcr.io/pkgforge-dev/archlinux:latest
    name: "Appimage (${{ matrix.target }})"
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          chmod +x ./linux-dependencies.sh
          ./linux-dependencies.sh
          
      - name: Clone Eden
        run: |
          git clone 'https://git.eden-emu.dev/eden-emu/eden.git' ./eden

      - name: Restore ccache for ${{ matrix.target }}
        if: ${{ matrix.ccache == 'true'}}
        uses: actions/cache/restore@v4
        id: restore-ccache-appimage
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.target }}-

      - name: Compile Eden ${{ matrix.target }}
        run: |
          chmod +x ./eden-appimage.sh
          ./eden-appimage.sh ${{ matrix.target }}

      - name: Save ccache for ${{ matrix.target }}
        if: ${{ matrix.ccache == 'true' && github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.restore-ccache-appimage.outputs.cache-primary-key }}

      - name: Upload appimage
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-${{ matrix.target}}-appimage
          path: eden/appimage

      - name: Upload appbundle
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-${{ matrix.target}}-appbundle
          path: eden/appbundle
  
  release:
    if: github.ref_name == 'main' && github.event.inputs.job_to_run == 'all'
    name: "release"
    needs: [info, appimage]
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v5.0.0
        with:
          pattern: "*"
          merge-multiple: true

      - name: Generate changelog
        run: |
          echo "TAG=$(cat tag)" >> "${GITHUB_ENV}"
          echo "COUNT=$(cat count)" >> "${GITHUB_ENV}"
          echo "BODY<<EOF" >> "${GITHUB_ENV}"
          cat changelog >> "${GITHUB_ENV}"
          echo "EOF" >> "${GITHUB_ENV}"

      - name: Release Eden
        uses: softprops/action-gh-release@v2.4.1
        with:
          name: "Eden Unofficial Nightly Release: ${{ env.COUNT }}"
          tag_name: "${{ env.TAG }}"
          body: "${{ env.BODY }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            *.AppImage*, *.AppBundle*, *.7z, *.tar.xz
